# VPS监控系统 v1.0 - Docker Compose配置
# 作者: kure29
# 网站: https://kure29.com

version: '3.8'

services:
  vps-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vps-monitor-v1
    restart: unless-stopped
    
    # 环境变量
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    
    # 挂载卷
    volumes:
      - ./config.json:/app/config.json:ro
      - ./urls.json:/app/urls.json
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backup:/app/backup
    
    # 网络配置
    networks:
      - vps-monitor-network
    
    # 端口映射（如果有Web界面）
    ports:
      - "8000:8000"
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 依赖服务（如果需要）
    depends_on:
      - redis
      
  # Redis服务（可选，用于缓存）
  redis:
    image: redis:7-alpine
    container_name: vps-monitor-redis
    restart: unless-stopped
    
    # 命令
    command: redis-server --appendonly yes
    
    # 挂载卷
    volumes:
      - redis-data:/data
    
    # 网络配置
    networks:
      - vps-monitor-network
    
    # 健康检查
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'

  # Nginx反向代理（可选，用于Web界面）
  nginx:
    image: nginx:alpine
    container_name: vps-monitor-nginx
    restart: unless-stopped
    
    # 端口映射
    ports:
      - "80:80"
      - "443:443"
    
    # 挂载卷
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    
    # 网络配置
    networks:
      - vps-monitor-network
    
    # 依赖服务
    depends_on:
      - vps-monitor
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# 网络定义
networks:
  vps-monitor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 卷定义
volumes:
  redis-data:
    driver: local
  monitor-data:
    driver: local
  monitor-logs:
    driver: local
  monitor-backup:
    driver: local

# 扩展配置
x-common-variables: &common-variables
  TZ: Asia/Shanghai
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
